### ISSUE TITLE
AUR Release

### ISSUE THREAD

**Issue by OmegaRogue** [cbrake/arch-kicad-8#1]
This package would be good to have on the AUR properly instead of just being a github repo set up identical to an AUR git repo

**Comment by cbrake** [comment]
you are probably right, however, this is hopefully a short-term thing as KiCad8 should be in the main feeds now that it is released. If this turns into a long-term situation, then I'll reconsider.

**Comment by OmegaRogue** [comment]
> you are probably right, however, this is hopefully a short-term thing as KiCad8 should be in the main feeds now that it is released. If this turns into a long-term situation, then I'll reconsider.

it can always be pulled from the AUR again, putting it on the AUR would consist of pushing this repo to the AUR

**Comment by cbrake** [comment]
It looks like KiCad 8 is landing in main repos soon:

![image](https://github.com/cbrake/arch-kicad-8/assets/402813/4d93a0a2-3b1a-4fd6-9e32-bb63f12ff56c)

So hopefully this recipe will be obsolete before I get around to cleaning it up.

Appreciate the suggestion though -- will consider going directly to the AUR next time.

**Comment by OmegaRogue** [comment]
![image](https://github.com/cbrake/arch-kicad-8/assets/24958536/188f780d-fc84-46cc-8dc8-128605c04d33)
still in testing and 8.0.1 is out

**Comment by cbrake** [comment]
8.0.1 is in the main feeds:

https://archlinux.org/packages/?q=kicad

Added a note to the README in this repo.

Sorry, I could not be more responsive to your suggestions due to lack of time here -- will keep in mind for next time.
